module.exports = {
	listingsData:[
		{
			EntityType:"Resale",
			PriceType:"Default",
			Status:"Active",
			IsExclusive:"false",
			IsForeclosure:"false",
			IsFeatured:"false",
			HideAddress:"false",
			Amenities:[],
			PrivacyLevel:"Public",
			Address:"Miami",
			RefNumber:"88750033",
			country:"us",
			LocationText:"Miami, Florida",
			Currency:"USD",
			Price:2450000,
			ContractType:"Sale",
			Types:["Other"],
			BuiltArea:{"Value":"3500","Unit":"squarefoot"},
			Headlines:[{"Language":"en","Value":"Miami Luxury House","Default":"true"}],
			Descriptions:[{"Language":"en","Value":"Call me right now.","Default":"true"}],
			LatLong:[25.7616798,-80.1917902]
		},
		{
			EntityType:"Resale",
			PriceType:"Default",
			Status:"Active",
			IsExclusive:"false",
			IsForeclosure:"false",
			IsFeatured:"false",
			HideAddress:"false",
			Amenities:[],
			PrivacyLevel:"Public",
			Address:"Miami Beach",
			RefNumber:"990033221",
			country:"us",
			LocationText:"Miami Beach, Florida",
			Currency:"USD",
			Price:850000,
			ContractType:"Sale",
			Types:["Other"],
			BuiltArea:{"Value":"3500","Unit":"squarefoot"},
			Headlines:[{"Language":"en","Value":"Miami Beach house","Default":"true"}],
			Descriptions:[{"Language":"en","Value":"Visit this property.","Default":"true"}],
			LatLong:[25.790654,-80.1300455]
		},
	],
};
